### ISSUE TITLE
(Question)Can you create a low version for this port?

### ISSUE THREAD

**Issue by Wtfguvuhvyh** [burnedpopcorn/PT-Scoutdigo-Web-Port#1]
Because my phone is too poor, this port cannot work on joiplay(this is an app that it can run HTML5). So, can you create a low version for this port? Just remove all music and sound effects from this port.

**Comment by Wtfguvuhvyh** [comment]
Of course, it's okay if you don't want to do it

**Comment by burnedpopcorn** [comment]
I mean, I always thought of doing that for the main Port once I got sound working on that one, so I might do it here when I can

Although this won't be high priority
