### ISSUE TITLE
Port to gx.games/autistici

### ISSUE THREAD

**Issue by ThePeppinoSpaghetti** [burnedpopcorn/PT-Scoutdigo-Web-Port#2]
Chances are my phone won't run this, yet my laggy chromebook can somehow run cheesed up at a decent speed. Sometimes, it goes above the device refresh rate! So since I still want to play this, can you port it to gx.games/autistici? Thanks!

**Comment by burnedpopcorn** [comment]
The Scoutdigo port is already being hosted on autistici servers...

**Comment by burnedpopcorn** [comment]
And GX.GAMES hosting it is out of the question, unless I make another custom launcher,  but that's basically just a redirect to my site that already hosts it
