### ISSUE TITLE
MISSING KEYS 

### ISSUE THREAD

**Issue by Goofybro7** [burnedpopcorn/PT-Scoutdigo-Web-Port#3]
Self explanatory but some of the secret keys are not there so.. yea

Plus is there any debug thing and nicnaks

**Comment by burnedpopcorn** [comment]
What Levels have Missing Keys?

And also I haven't got around to fixing Commands, as this is just an Initial Release

**Comment by Goofybro7** [comment]
its not in levels its in the lobby things 
here: https://www.youtube.com/watch?v=DgdyizPEvug

**Comment by Goofybro7** [comment]
OMG THEY WERE FAKE KEYS bruuuu

**Comment by Goofybro7** [comment]
nvm

**Comment by burnedpopcorn** [comment]
lol, you really do have a fitting name
