### ISSUE TITLE
I might buy a chromebook

### ISSUE THREAD

**Issue by BFDIFirey** [burnedpopcorn/PT-Scoutdigo-Web-Port#4]
I said I might

**Comment by burnedpopcorn** [comment]
Why would you buy a chromebook. Don't you already have a computer?

**Comment by BFDIFirey** [comment]
I broke it (I was playing TF2 and I broke the screen...)

**Comment by burnedpopcorn** [comment]
That's crazy

Also hello fellow TF2 player
