### ISSUE TITLE
Hitting John in TCTOP makes the screen go white

### ISSUE THREAD

**Issue by ShyGuyComputer** [burnedpopcorn/PT-Scoutdigo-Web-Port#6]
Goes back to normal once you enter the next room

**Comment by burnedpopcorn** [comment]
Yeah, got no idea what causes it. Maybe a shader? Gonna check code related to BloodSauce Dunegon, cuz the dark rooms also have that issue

**Comment by ShyGuyComputer** [comment]
This also happens when getting caught by Pizzaface in Death Mode

**Comment by burnedpopcorn** [comment]
Fixed

Except Pizzaface in Death Mode thing you mentioned
I didn't check that
