### ISSUE TITLE
painting key not there

### ISSUE THREAD

**Issue by pepperman2023** [burnedpopcorn/PT-Scoutdigo-Web-Port#7]
im collecting all the keys and the painting key doesn't work,normally you would knock them down by superjumping to the ceiling above them but when i did that they just stood there,i tried all of them but no key spawned and no paintings fell

**Comment by Wtfguvuhvyh** [comment]
No, these keys can be collected normally
(Here is a picture of one of my friends successfully collecting keys)
![Image_1721532270400](https://github.com/user-attachments/assets/5f55013b-9a76-4ff3-8e14-4da81575eb9e)

**Comment by pepperman2023** [comment]
kay but thats the wrong key room,still helpful thx!
