### ISSUE TITLE
are you able to make a web port of lap 10 in pizza tower

### ISSUE THREAD

**Issue by chubbybelly24** [burnedpopcorn/PT-Scoutdigo-Web-Port#8]
hi its me again are you able to make a web port of lap 10 in pizza tower

**Comment by burnedpopcorn** [comment]
My Cheesed Up web port has infinite laps
So go check that port out

**Comment by chubbybelly24** [comment]
yeah but it doesn't have the characters for lap 10 and no checkpoints

**Comment by chubbybelly24** [comment]
it just pulls back the time

**Comment by burnedpopcorn** [comment]
I don't do xdelta mods, nor is the source code available to my knowledge, so I can't port that mod

**Comment by chubbybelly24** [comment]
or just add it in pizza tower web port and also I was right, the video is laggy but not the game it self I'll post the video in discord

**Comment by chubbybelly24** [comment]
it says I cant send messeges username: chubbybell

**Comment by chubbybelly24** [comment]
I'll try to get the source code
